"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { deleteReport, getStudentClass, listReports, listTeacherReports, saveReport as saveReportToDb, signInTeacher, supabaseConfigured, verifyStudentAccess, type SavedReport, type TeacherSession } from "../lib/supabase-rest";

type Point = { x: string; y: string };
type ChartType = "line" | "bar" | "pie" | "band" | "scatter";

const initialRows: Point[] = [{ x: "0", y: "25.0" }, { x: "2", y: "42.0" }, { x: "4", y: "61.0" }, { x: "6", y: "78.0" }, { x: "8", y: "95.0" }, { x: "10", y: "100.0" }];
const variableOptions = ["시간", "온도", "압력", "부피", "질량", "무게", "힘의 크기", "길이"];
const unitOptions = ["℃", "g", "kg", "N", "mL", "L", "mm", "cm", "m", "기압", "s", "min"];
const chartLabels: Record<ChartType, string> = { line: "꺾은선 그래프", bar: "막대그래프", pie: "원그래프", band: "띠그래프", scatter: "점그래프(산점도)" };

function numberOf(value: string) { return Number(value.trim()); }
function validRows(rows: Point[]) { return rows.filter((row) => Number.isFinite(numberOf(row.x)) && Number.isFinite(numberOf(row.y))); }

function Graph({ points, xName, yName, xUnit, yUnit, chartType, compact = false }: { points: Point[]; xName: string; yName: string; xUnit: string; yUnit: string; chartType: ChartType; compact?: boolean }) {
  const ref = useRef<HTMLCanvasElement>(null);
  useEffect(() => {
    const canvas = ref.current; if (!canvas) return;
    const ratio = window.devicePixelRatio || 1; const width = canvas.clientWidth; const height = canvas.clientHeight;
    canvas.width = width * ratio; canvas.height = height * ratio;
    const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.setTransform(ratio, 0, 0, ratio, 0, 0); ctx.clearRect(0, 0, width, height);
    const left = compact ? 48 : 62, right = 24, top = 28, bottom = compact ? 42 : 54, cw = width - left - right, ch = height - top - bottom;
    const xs = points.map((p) => numberOf(p.x)), ys = points.map((p) => numberOf(p.y));
    const minX = xs.length ? Math.min(...xs) : 0, maxX = xs.length ? Math.max(...xs) : 10, minY = ys.length ? Math.min(...ys) : 0, maxY = ys.length ? Math.max(...ys) : 10;
    const xPad = Math.max((maxX - minX) * .08, 1), yPad = Math.max((maxY - minY) * .14, 1); const x0 = minX >= 0 ? 0 : minX - xPad; const y0 = minY >= 0 ? 0 : minY - yPad; const x1 = maxX + xPad; const y1 = maxY + yPad;
    const px = (x: number) => left + ((x - x0) / Math.max(x1 - x0, 1)) * cw; const py = (y: number) => top + ch - ((y - y0) / Math.max(y1 - y0, 1)) * ch;
    ctx.font = `${compact ? 10 : 12}px Arial`; ctx.strokeStyle = "#dce8f7"; ctx.fillStyle = "#60749a"; ctx.lineWidth = 1;
    for (let i = 0; i <= 5; i += 1) { const gx = left + cw * i / 5, gy = top + ch * i / 5; ctx.beginPath(); ctx.moveTo(gx, top); ctx.lineTo(gx, top + ch); ctx.stroke(); ctx.beginPath(); ctx.moveTo(left, gy); ctx.lineTo(left + cw, gy); ctx.stroke(); ctx.fillText((x0 + (x1 - x0) * i / 5).toFixed(1), gx - 10, top + ch + (compact ? 17 : 22)); ctx.fillText((y1 - (y1 - y0) * i / 5).toFixed(1), 4, gy + 4); }
    ctx.strokeStyle = "#245cff"; ctx.lineWidth = 1.6; ctx.beginPath(); ctx.moveTo(left, top); ctx.lineTo(left, top + ch); ctx.lineTo(left + cw, top + ch); ctx.stroke();
    if (chartType === "pie" && points.length) { const total = ys.reduce((sum, value) => sum + Math.max(value, 0), 0) || 1; let start = -Math.PI / 2; points.forEach((point, index) => { const slice = Math.max(numberOf(point.y), 0) / total * Math.PI * 2; ctx.beginPath(); ctx.moveTo(width / 2, top + ch / 2); ctx.arc(width / 2, top + ch / 2, Math.min(cw, ch) * .36, start, start + slice); ctx.closePath(); ctx.fillStyle = ["#155dff", "#00acd0", "#6d45e8", "#37c394", "#f0b638", "#ff7590"][index % 6]; ctx.fill(); ctx.strokeStyle = "#fff"; ctx.lineWidth = 2; ctx.stroke(); start += slice; }); }
    else if (chartType === "bar") { const barWidth = Math.max(8, cw / Math.max(points.length * 1.7, 2)); points.forEach((point, index) => { const x = left + cw * (index + .5) / points.length; const topY = py(numberOf(point.y)); ctx.fillStyle = "#3872ed"; ctx.fillRect(x - barWidth / 2, topY, barWidth, top + ch - topY); }); }
    else if (chartType === "band") { const bandY = top + ch * .43; ctx.fillStyle = "#9cc7ee"; ctx.fillRect(left, bandY, cw, ch * .22); ctx.strokeStyle = "#1688cc"; ctx.lineWidth = 2; ctx.strokeRect(left, bandY, cw, ch * .22); points.forEach((_, index) => { const x = left + cw * (index + .5) / points.length; ctx.fillStyle = "#175bda"; ctx.fillRect(x - 2, bandY - 8, 4, ch * .22 + 16); }); }
    else { if (chartType === "line" && points.length) { ctx.beginPath(); points.forEach((point, index) => index ? ctx.lineTo(px(numberOf(point.x)), py(numberOf(point.y))) : ctx.moveTo(px(numberOf(point.x)), py(numberOf(point.y)))); ctx.strokeStyle = "#245cff"; ctx.lineWidth = 2.8; ctx.stroke(); } points.forEach((point) => { ctx.beginPath(); ctx.arc(px(numberOf(point.x)), py(numberOf(point.y)), compact ? 4 : 6, 0, Math.PI * 2); ctx.fillStyle = "#0b8fc5"; ctx.fill(); ctx.strokeStyle = "#fff"; ctx.lineWidth = 2; ctx.stroke(); }); }
    ctx.fillStyle = "#304d7d"; ctx.font = `600 ${compact ? 10 : 12}px Arial`; ctx.fillText(`${yName || "종속 변인"}${yUnit ? ` (${yUnit})` : ""}`, left, 14); ctx.fillText(`${xName || "독립 변인"}${xUnit ? ` (${xUnit})` : ""}`, Math.max(left, width / 2 - 40), height - 8);
  }, [points, xName, yName, xUnit, yUnit, chartType, compact]);
  return <canvas ref={ref} className={compact ? "graph-canvas compact" : "graph-canvas"} aria-label="실험 데이터 그래프" />;
}

function TeacherReportView({ report, onBack }: { report: SavedReport; onBack: () => void }) {
  const data = report.report_data;
  const points = validRows(data.rows);
  return <section className="teacher-report-view"><div className="result-actions no-print"><button className="secondary-button" onClick={onBack}>← 목록으로</button><button className="primary-button" onClick={() => window.print()}>인쇄 / PDF 저장</button></div><article className="report"><header><div className="report-kicker">탐구한장 · SCIENCE EXPERIMENT REPORT</div><h2>실험 결과지</h2><p>학번: {report.student_name}</p></header><section><h3>1. 실험 제목</h3><p className="answer strong">{data.title || "입력하지 않음"}</p></section><section><h3>2. 실험 목표</h3><p className="answer">{data.goal || "입력하지 않음"}</p></section><div className="report-grid"><section><h3>3. 실험 결과 표</h3><table><thead><tr><th>횟수</th><th>{data.xName} ({data.xUnit})</th><th>{data.yName} ({data.yUnit})</th></tr></thead><tbody>{points.map((point, index) => <tr key={index}><td>{index + 1}</td><td>{point.x}</td><td>{point.y}</td></tr>)}</tbody></table></section><section><h3>4. 그래프</h3><Graph points={points} xName={data.xName} yName={data.yName} xUnit={data.xUnit} yUnit={data.yUnit} chartType={data.chartType as ChartType} compact /></section></div><section><h3>5. 결과 분석</h3><p className="answer">{data.analysis || "작성하지 않음"}</p></section><section><h3>6. 과학적 원리</h3><p className="answer">{data.principle || "작성하지 않음"}</p></section><section><h3>7. 오차 원인</h3><p className="answer">{data.errorCause || "작성하지 않음"}</p></section><section><h3>8. 결론</h3><p className="answer">{data.conclusion || "작성하지 않음"}</p></section></article></section>;
}

function TeacherReportGroups({ reports, onSelect }: { reports: SavedReport[]; onSelect: (report: SavedReport) => void }) {
  const groups = reports.reduce<Record<string, SavedReport[]>>((result, report) => { (result[report.student_name] ||= []).push(report); return result; }, {});
  return <div className="teacher-groups">{Object.entries(groups).map(([studentCode, studentReports]) => <section className="teacher-group" key={studentCode}><h2>학번 {studentCode}<span>{studentReports.length}건</span></h2><div className="teacher-report-list">{studentReports.map((report) => <button className="teacher-report-item" key={report.id} onClick={() => onSelect(report)}><strong>{report.title}</strong><span>{new Date(report.created_at).toLocaleString("ko-KR")}</span></button>)}</div></section>)}</div>;
}

function TeacherClassGroups({ reports, onSelect }: { reports: SavedReport[]; onSelect: (report: SavedReport) => void }) {
  const [selectedClass, setSelectedClass] = useState<number | null>(null);
  const classReports = selectedClass === null ? [] : reports.filter((report) => report.class_number === selectedClass);
  if (selectedClass !== null) return <div className="teacher-class-detail"><button className="secondary-button" onClick={() => setSelectedClass(null)}>← 반 목록</button><h2 className="teacher-class-title">{selectedClass}반 학생 보고서</h2><TeacherReportGroups reports={classReports} onSelect={onSelect} /></div>;
  return <div className="teacher-class-grid">{Array.from({ length: 9 }, (_, index) => index + 1).map((classNumber) => <button className="teacher-class-card" key={classNumber} onClick={() => setSelectedClass(classNumber)}><strong>{classNumber}반</strong><span>{reports.filter((report) => report.class_number === classNumber).length}건</span><small>학번별 보고서 보기 →</small></button>)}</div>;
}

export default function Home() {
  const [step, setStep] = useState(1); const [title, setTitle] = useState(""); const [student, setStudent] = useState(""); const [goal, setGoal] = useState("");
  const [xName, setXName] = useState("시간"); const [xUnit, setXUnit] = useState("min"); const [yName, setYName] = useState("온도"); const [yUnit, setYUnit] = useState("℃"); const [rows, setRows] = useState<Point[]>(initialRows); const [chartType, setChartType] = useState<ChartType>("line");
  const [analysis, setAnalysis] = useState(""); const [principle, setPrinciple] = useState(""); const [errorCause, setErrorCause] = useState(""); const [conclusion, setConclusion] = useState(""); const [notice, setNotice] = useState("");
  const [savedReports, setSavedReports] = useState<SavedReport[]>([]); const [showSaved, setShowSaved] = useState(false); const [dbBusy, setDbBusy] = useState(false);
  const [verifiedStudent, setVerifiedStudent] = useState<string | null>(null); const [verifiedClass, setVerifiedClass] = useState<number | null>(null); const [accessCode, setAccessCode] = useState(""); const [accessPin, setAccessPin] = useState(""); const [accessBusy, setAccessBusy] = useState(false); const [accessNotice, setAccessNotice] = useState("");
  const [teacherSession, setTeacherSession] = useState<TeacherSession | null>(null); const [teacherEmail, setTeacherEmail] = useState(""); const [teacherPassword, setTeacherPassword] = useState(""); const [teacherReports, setTeacherReports] = useState<SavedReport[]>([]); const [teacherSelectedClass, setTeacherSelectedClass] = useState<number | null>(null); const [teacherSelectedReport, setTeacherSelectedReport] = useState<SavedReport | null>(null); const [teacherBusy, setTeacherBusy] = useState(false); const [teacherNotice, setTeacherNotice] = useState(""); const [accessMode, setAccessMode] = useState<"student" | "teacher">("student");
  const points = useMemo(() => validRows(rows), [rows]);
  const updateRow = (index: number, field: keyof Point, event: ChangeEvent<HTMLInputElement>) => setRows((current) => current.map((row, i) => i === index ? { ...row, [field]: event.target.value } : row));
  const refreshReports = async () => { if (!supabaseConfigured) return; try { setSavedReports(await listReports()); } catch (error) { const detail = error instanceof Error && error.message ? ` (${error.message})` : ""; setNotice(`Supabase 목록을 불러오지 못했습니다${detail}. SQL Editor에서 db/supabase.sql을 실행해 주세요.`); } };
  useEffect(() => { void refreshReports(); }, []);
  const reportData = () => ({ title, student, goal, xName, xUnit, yName, yUnit, rows, chartType, analysis, principle, errorCause, conclusion });
  const saveReport = async () => { if (!supabaseConfigured) { setNotice("Vercel 설정에 NEXT_PUBLIC_SUPABASE_URL과 NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY를 등록한 뒤 Redeploy해 주세요."); return; } if (!title.trim() || !student.trim()) { setNotice("보고서 저장을 위해 실험 제목과 학번을 입력해 주세요."); return; } setDbBusy(true); try { await saveReportToDb({ title, student_name: student, report_data: reportData() }); await refreshReports(); setNotice("보고서가 Supabase DB에 저장되었습니다."); setShowSaved(true); } catch (error) { const detail = error instanceof Error && error.message ? ` (${error.message})` : ""; setNotice(`보고서 저장에 실패했습니다${detail}. Supabase SQL Editor에서 experiment_reports INSERT 정책을 다시 실행해 주세요.`); } finally { setDbBusy(false); } };
  const restoreReport = (report: SavedReport) => { const data = report.report_data; setTitle(data.title); setStudent(data.student); setGoal(data.goal); setXName(data.xName); setXUnit(data.xUnit); setYName(data.yName); setYUnit(data.yUnit); setRows(data.rows); setChartType(data.chartType as ChartType); setAnalysis(data.analysis); setPrinciple(data.principle); setErrorCause(data.errorCause); setConclusion(data.conclusion); setStep(1); setShowSaved(false); setNotice("저장된 보고서를 불러왔습니다."); };
  const removeReport = async (id: string) => { if (!supabaseConfigured) return; setDbBusy(true); try { await deleteReport(id); await refreshReports(); } catch { setNotice("보고서 삭제에 실패했습니다."); } finally { setDbBusy(false); } };
  const goGraph = () => { if (points.length < 2) { setNotice("그래프를 만들려면 숫자로 된 측정값을 2개 이상 입력해 주세요."); return; } setNotice(""); setStep(2); };

  useEffect(() => { const savedStudent = window.sessionStorage.getItem("탐구한장:student"); if (savedStudent) { setVerifiedStudent(savedStudent); setStudent(savedStudent); } }, []);
  const verifyAccess = async () => { if (!supabaseConfigured) { setAccessNotice("먼저 Vercel에 Supabase 환경변수를 등록해 주세요."); return; } if (!accessCode.trim() || !accessPin.trim()) { setAccessNotice("학번과 PIN을 모두 입력해 주세요."); return; } setAccessBusy(true); setAccessNotice(""); try { const valid = await verifyStudentAccess(accessCode.trim(), accessPin.trim()); if (!valid) { setAccessNotice("학번 또는 PIN이 올바르지 않습니다."); return; } window.sessionStorage.setItem("탐구한장:student", accessCode.trim()); setVerifiedStudent(accessCode.trim()); setStudent(accessCode.trim()); void refreshReports(); } catch { setAccessNotice("학생 인증에 실패했습니다. Supabase student_access 설정을 확인해 주세요."); } finally { setAccessBusy(false); } };
  const signOutStudent = () => { window.sessionStorage.removeItem("탐구한장:student"); setVerifiedStudent(null); setSavedReports([]); setShowSaved(false); setStep(1); };
  const newReport = () => { setTitle(""); setGoal(""); setRows(initialRows); setChartType("line"); setAnalysis(""); setPrinciple(""); setErrorCause(""); setConclusion(""); setNotice(""); setStep(1); setShowSaved(false); };
  const teacherLogin = async () => { if (!teacherEmail.trim() || !teacherPassword) { setTeacherNotice("교사 이메일과 비밀번호를 입력해 주세요."); return; } setTeacherBusy(true); setTeacherNotice(""); try { const session = await signInTeacher(teacherEmail.trim(), teacherPassword); const reports = await listTeacherReports(session.access_token); setTeacherSession(session); setVerifiedStudent(null); setTeacherReports(reports); } catch (error) { const detail = error instanceof Error && error.message ? ` (${error.message})` : ""; setTeacherNotice(`교사 로그인 또는 권한 확인에 실패했습니다${detail}。 Supabase Auth 계정, 이메일 확인 상태, teacher_profiles 등록을 확인해 주세요.`); } finally { setTeacherBusy(false); } };
  const teacherLogout = () => { setTeacherSession(null); setTeacherReports([]); setTeacherSelectedReport(null); setTeacherEmail(""); setTeacherPassword(""); setAccessMode("student"); };
  const restoreTeacherReport = (report: SavedReport) => { setTeacherSelectedReport(report); };
  if (teacherSession) return <main className="lab-shell teacher-shell"><header className="topbar"><button className="brand" onClick={() => setTeacherSelectedReport(null)}><span className="brand-mark">탐</span><span>탐구한장</span></button><span className="topbar-sub">교사 보고서 관리</span><button className="signout-button" onClick={teacherLogout}>로그아웃</button></header>{teacherSelectedReport ? <TeacherReportView report={teacherSelectedReport} onBack={() => setTeacherSelectedReport(null)} /> : <section className="teacher-dashboard"><div className="teacher-heading"><div><div className="eyebrow">TEACHER DASHBOARD</div><h1>학생 탐구보고서</h1><p>반별로 묶어 저장된 실험 결과지를 확인할 수 있어요.</p></div><strong>{teacherReports.length}건</strong></div>{teacherReports.length === 0 ? <div className="db-empty">저장된 보고서가 없습니다.</div> : <TeacherClassGroups reports={teacherReports} onSelect={restoreTeacherReport} />}</section>}</main>;
  if (!verifiedStudent) return <main className="lab-shell access-shell"><section className="access-card"><div className="brand-mark">탐</div><div className="eyebrow">SCIENCE EXPERIMENT REPORT</div>{accessMode === "student" ? <><h1>탐구한장에<br /><em>입장하기</em></h1><p>선생님에게 받은 학번과 PIN을 입력하면<br />나의 실험 보고서를 확인할 수 있어요.</p><label>학번<input value={accessCode} onChange={(event) => setAccessCode(event.target.value)} placeholder="예: 11111" inputMode="numeric" /></label><label>PIN<input value={accessPin} onChange={(event) => setAccessPin(event.target.value)} placeholder="선생님이 제공한 PIN" type="password" inputMode="numeric" /></label>{accessNotice && <p className="access-notice" role="alert">{accessNotice}</p>}<button className="primary-button access-submit" disabled={accessBusy} onClick={() => void verifyAccess()}>{accessBusy ? "확인 중..." : "탐구한장 시작하기 →"}</button><button className="access-switch" onClick={() => { setAccessMode("teacher"); setAccessNotice(""); }}>교사용 보고서 보기</button><small>학생별 보고서는 입력한 학번에 연결되어 누적 저장됩니다.</small></> : <><h1>교사 <em>로그인</em></h1><p>Supabase Auth에 등록된 교사 계정으로<br />학생 보고서를 확인할 수 있어요.</p><label>교사 이메일<input type="email" value={teacherEmail} onChange={(event) => setTeacherEmail(event.target.value)} placeholder="teacher@example.com" /></label><label>비밀번호<input value={teacherPassword} onChange={(event) => setTeacherPassword(event.target.value)} placeholder="비밀번호" type="password" /></label>{teacherNotice && <p className="access-notice" role="alert">{teacherNotice}</p>}<button className="primary-button access-submit" disabled={teacherBusy} onClick={() => void teacherLogin()}>{teacherBusy ? "로그인 중..." : "교사 대시보드 입장 →"}</button><button className="access-switch" onClick={() => { setAccessMode("student"); setTeacherNotice(""); }}>학생 입장으로 돌아가기</button></>}</section></main>;

  return <main className="lab-shell">
    <header className="topbar"><button className="brand" onClick={() => { setStep(1); setNotice(""); }}><span className="brand-mark">탐</span><span>탐구한장</span></button><span className="topbar-sub">과학 실험 데이터 시각화 · 결과지 작성</span><div className="db-actions"><button className="saved-button" onClick={() => { setShowSaved((value) => !value); void refreshReports(); }}>▤ 내 저장 보고서 <b>{savedReports.length}</b></button><span className={supabaseConfigured ? "db-status connected" : "db-status"}>{supabaseConfigured ? "DB 연결됨" : "DB 설정 필요"}</span><button className="signout-button" onClick={signOutStudent}>나가기</button></div></header>
    <section className="hero"><div><div className="eyebrow">SCIENCE EXPERIMENT REPORT</div><h1>실험 데이터를 한 장의<br /><em>탐구 결과지</em>로 완성해요.</h1><p>측정값을 입력하면 실제 수치 간격을 반영한 그래프가 만들어지고,<br />간단한 질문에 답하며 실험 결과를 정리할 수 있어요.</p></div><div className="hero-note character-note"><div className="student-character"><span>🧑‍🔬</span><i>⚗</i></div><small>오늘의 실험</small><strong>측정하고, 관찰하고,<br />탐구를 완성해요!</strong></div></section>
    {showSaved && <section className="saved-panel"><div><h2>내 저장 보고서</h2><p>Supabase에 저장된 탐구보고서를 다시 열어볼 수 있어요.</p></div>{!supabaseConfigured ? <div className="db-empty">Supabase 환경변수를 설정하면 저장 목록이 나타납니다.</div> : savedReports.length === 0 ? <div className="db-empty">아직 저장된 보고서가 없습니다.</div> : <div className="saved-list">{savedReports.map((report) => <div className="saved-row" key={report.id}><button onClick={() => restoreReport(report)}><strong>{report.title}</strong><small>학번 {report.student_name} · {new Date(report.created_at).toLocaleString("ko-KR")}</small></button><button className="saved-delete" disabled={dbBusy} onClick={() => void removeReport(report.id)}>삭제</button></div>)}</div>}</section>}
    <nav className="steps" aria-label="보고서 작성 단계"><button className={step === 1 ? "active" : step > 1 ? "done" : ""} onClick={() => step > 1 && setStep(1)}><b>1</b><span>실험 데이터 입력</span><small>측정값과 변인</small></button><i /><button className={step === 2 ? "active" : step > 2 ? "done" : ""} onClick={() => step > 2 && setStep(2)}><b>2</b><span>그래프 및 분석</span><small>변화 관계 해석</small></button><i /><button className={step === 3 ? "active" : ""} onClick={() => step === 3 && setStep(3)}><b>3</b><span>실험 결과지</span><small>한 장으로 완성</small></button></nav>
    {notice && <p className="notice" role="alert">{notice}</p>}
    {step === 1 && <section className="workspace two-col"><div className="card"><div className="section-title"><span>01</span><div><h2>기본 정보</h2><p>실험의 제목과 변인을 입력해 주세요.</p></div></div><label>실험 제목<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="예: 물이 끓을 때의 온도 측정하기" /></label><label>학번<input value={student} onChange={(e) => setStudent(e.target.value)} placeholder="예: 202470509" /></label><label>실험 목표<textarea value={goal} onChange={(e) => setGoal(e.target.value)} placeholder="예: 물이 끓을 때의 온도를 측정하여 그래프로 나타낼 수 있다." /></label><div className="section-title compact-title"><span>02</span><div><h2>변인 설정</h2><p>독립 변인과 종속 변인, 단위를 선택해 주세요.</p></div></div><div className="variable-grid"><label>독립 변인<select value={xName} onChange={(e) => setXName(e.target.value)}>{variableOptions.map((option) => <option key={option}>{option}</option>)}</select></label><label>단위<select value={xUnit} onChange={(e) => setXUnit(e.target.value)}>{unitOptions.map((option) => <option key={option}>{option}</option>)}</select></label><label>종속 변인<select value={yName} onChange={(e) => setYName(e.target.value)}>{variableOptions.map((option) => <option key={option}>{option}</option>)}</select></label><label>단위<select value={yUnit} onChange={(e) => setYUnit(e.target.value)}>{unitOptions.map((option) => <option key={option}>{option}</option>)}</select></label></div></div><div className="card"><div className="section-title"><span>03</span><div><h2>측정 데이터</h2><p>정수와 소수점 값을 그대로 입력해 주세요.</p></div></div><div className="table-wrap"><table><thead><tr><th>횟수</th><th>{xName} ({xUnit})</th><th>{yName} ({yUnit})</th><th /></tr></thead><tbody>{rows.map((row, index) => <tr key={index}><td>{index + 1}</td><td><input inputMode="decimal" value={row.x} onChange={(e) => updateRow(index, "x", e)} /></td><td><input inputMode="decimal" value={row.y} onChange={(e) => updateRow(index, "y", e)} /></td><td>{rows.length > 2 && <button className="delete-row" onClick={() => setRows((current) => current.filter((_, i) => i !== index))}>×</button>}</td></tr>)}</tbody></table></div><div className="data-actions"><button className="secondary-button" onClick={() => setRows((current) => [...current, { x: "", y: "" }])}>＋ 행 추가</button><button className="primary-button" onClick={goGraph}>그래프 만들기 <span>→</span></button></div><div className="data-tip"><b>ⓘ</b><span><strong>소수점까지 정확하게 입력해 주세요!</strong><br />실제 수치 간격으로 그래프에 표시됩니다.</span></div></div></section>}
    {step === 2 && <section className="workspace graph-layout"><div className="card graph-panel"><div className="section-title"><span>01</span><div><h2>자동 생성된 그래프</h2><p>측정값 사이의 실제 간격을 반영합니다.</p></div></div><div className="mini-table"><table><thead><tr><th>횟수</th><th>{xName} ({xUnit})</th><th>{yName} ({yUnit})</th></tr></thead><tbody>{points.map((point, index) => <tr key={index}><td>{index + 1}</td><td>{point.x}</td><td>{point.y}</td></tr>)}</tbody></table></div><div className="graph-options"><span>그래프 유형</span><select value={chartType} onChange={(e) => setChartType(e.target.value as ChartType)}>{(Object.keys(chartLabels) as ChartType[]).map((type) => <option value={type} key={type}>{chartLabels[type]}</option>)}</select></div><Graph points={points} xName={xName} yName={yName} xUnit={xUnit} yUnit={yUnit} chartType={chartType} /></div><div className="card analysis-panel"><div className="section-title"><span>02</span><div><h2>결과 분석</h2><p>필요한 항목만 작성해도 다음 단계로 이동할 수 있어요.</p></div></div><label>결과 분석<textarea value={analysis} onChange={(e) => setAnalysis(e.target.value)} placeholder="그래프에서 어떤 변화가 보이나요?" /></label><label>과학적 원리<textarea value={principle} onChange={(e) => setPrinciple(e.target.value)} placeholder="이 결과와 관련된 과학적 원리는 무엇인가요?" /></label><label>오차 원인<textarea value={errorCause} onChange={(e) => setErrorCause(e.target.value)} placeholder="실험 결과에 영향을 준 오차 원인은 무엇인가요?" /></label><label>결론<textarea value={conclusion} onChange={(e) => setConclusion(e.target.value)} placeholder="실험을 통해 무엇을 알게 되었나요?" /></label><div className="data-actions"><button className="secondary-button" onClick={() => setStep(1)}>← 수정</button><button className="primary-button" onClick={() => setStep(3)}>결과지 미리보기 <span>→</span></button></div></div></section>}
    {step === 3 && <section className="result-area"><div className="result-actions no-print"><button className="secondary-button" onClick={newReport}>새 탐구한장 만들기</button><button className="secondary-button" disabled={dbBusy} onClick={() => void saveReport()}>▣ 보고서 저장</button><button className="secondary-button" onClick={() => setStep(2)}>← 수정하기</button><button className="primary-button" onClick={() => window.print()}>인쇄 / PDF 저장 <span>▣</span></button></div><article className="report"><header><div className="report-kicker">탐구한장 · SCIENCE EXPERIMENT REPORT</div><h2>실험 결과지</h2><p>학번: {student || "입력하지 않음"}</p></header><section><h3>1. 실험 제목</h3><p className="answer strong">{title || "실험 제목을 입력해 주세요."}</p></section><section><h3>2. 실험 목표</h3><p className="answer">{goal || "실험 목표를 입력해 주세요."}</p></section><div className="report-grid"><section><h3>3. 실험 결과 표</h3><table><thead><tr><th>횟수</th><th>{xName} ({xUnit})</th><th>{yName} ({yUnit})</th></tr></thead><tbody>{points.map((point, index) => <tr key={index}><td>{index + 1}</td><td>{point.x}</td><td>{point.y}</td></tr>)}</tbody></table></section><section><h3>4. 그래프</h3><Graph points={points} xName={xName} yName={yName} xUnit={xUnit} yUnit={yUnit} chartType={chartType} compact /></section></div><section><h3>5. 결과 분석</h3><p className="answer">{analysis || "작성하지 않음"}</p></section><section><h3>6. 과학적 원리</h3><p className="answer">{principle || "작성하지 않음"}</p></section><section><h3>7. 오차 원인</h3><p className="answer">{errorCause || "작성하지 않음"}</p></section><section><h3>8. 결론</h3><p className="answer">{conclusion || "작성하지 않음"}</p></section></article></section>}
    <footer>✣ 탐구한장 <span>한 장으로, 실험이 정리된다!</span><small>데이터 입력 → 자동 생성 → 한 장으로 완성</small></footer>
  </main>;
}
